# Generated by Django 4.2.2 on 2023-06-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название')),
                ('author', models.CharField(max_length=40, verbose_name='автор')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('description', models.TextField(max_length=5000, verbose_name='описание')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('is_published', models.BooleanField(verbose_name='публичность')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название')),
            ],
        ),
    ]
